#!/usr/bin/env bash
# Fetch the upstream projects this port builds on, at the exact commits it was
# made against, apply our patches, and generate the open-source BIOS backend.
# Nothing here needs (or touches) a game disc. Afterwards: android/build_apk.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RECOMP="$ROOT/digimon-recomp"

PORT_URL="https://gitlab.com/ethan4love/psx-recomp-port.git"
PORT_REV="978ea38eb594354724772ba611a22372e1809476"
PSXRECOMP_URL="https://gitlab.com/ethan4love/psxrecomp.git"
PSXRECOMP_BRANCH="fix/bss-memfill-overlap"
PSXRECOMP_REV="6daed93d1be27e80dd61d09f2b78fa64d249383b"
TINYCC_URL="https://github.com/TinyCC/tinycc.git"
TINYCC_REV="9db1105c32afd3dcf0c28b8186f08e63c761b2b5"

checkout() {   # url dir rev [branch]
    if [[ ! -d "$2/.git" ]]; then
        git clone ${4:+--branch "$4"} "$1" "$2"
    fi
    git -C "$2" checkout -q "$3"
}

apply_patch() {   # repo patch
    if git -C "$1" apply --reverse --check "$2" 2>/dev/null; then
        echo "already applied: $(basename "$2")"
    else
        git -C "$1" apply "$2"
        echo "applied: $(basename "$2")"
    fi
}

checkout "$PORT_URL" "$RECOMP" "$PORT_REV"
checkout "$PSXRECOMP_URL" "$RECOMP/psxrecomp" "$PSXRECOMP_REV" "$PSXRECOMP_BRANCH"
checkout "$TINYCC_URL" "$RECOMP/tinycc" "$TINYCC_REV"

apply_patch "$RECOMP/psxrecomp" "$ROOT/patches/psxrecomp-android.patch"
apply_patch "$RECOMP/tinycc" "$ROOT/patches/tinycc-resolve-host-symbols.patch"

# TinyCC's predefined-macro table (tccdefs_.h) is generated by its own build.
if [[ ! -f "$RECOMP/tinycc/tccdefs_.h" ]]; then
    (cd "$RECOMP/tinycc" && ./configure >/dev/null && make tccdefs_.h >/dev/null \
        && rm -f config.h config.mak)
fi

# The open-source OpenBIOS backend, recompiled to C (bios/openbios.bin ships
# with psxrecomp).
if [[ ! -f "$RECOMP/psxrecomp/generated/OpenBIOS_full.c" ]]; then
    cmake -S "$RECOMP/psxrecomp/recompiler" -B "$RECOMP/psxrecomp/recompiler/build" \
        -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF >/dev/null
    cmake --build "$RECOMP/psxrecomp/recompiler/build" --target psxrecomp-bios
    (cd "$RECOMP/psxrecomp" && recompiler/build/psxrecomp-bios --config bios/OpenBIOS.toml >/dev/null)
fi

echo
echo "Ready. Build the app with: android/build_apk.sh"
